// This file is auto-generated by rpc.compiler

using System;
using Acoross.Network.Rpc.Sync;

namespace Acoross.TestRpc.Nested
{
    interface RpcSync
    {
        bool Login(LoginReq req);
        bool Chat(ChatMsg req);
    }

    interface NotiSync
    {
        void NotiChat(ChatMsg message);
    }

    abstract class RpcClientSync : RpcClientSyncBase, RpcSync, NotiSync
    {
        protected RpcClientSync()
        {
            TryRegisterNoti<ChatMsg>((int)NotiTypes.NotiChat, NotiChat);
        }

        public bool Login(LoginReq req)
        {
            return CallRemoteProcedure<LoginReq, bool>((int)RpcTypes.Login, req);
        }

        public bool Chat(ChatMsg req)
        {
            return CallRemoteProcedure<ChatMsg, bool>((int)RpcTypes.Chat, req);
        }

        public abstract void NotiChat(ChatMsg message);
    }
}
