// This file is auto-generated by rpc.compiler

using System;
using System.Collections.Generic;
//using System.Threading.Tasks;

namespace Acoross.TestRpc.Nested
{
    public enum RpcTypes : int
    {
        Login, 
        Chat
    }

    public enum NotiTypes : int
    {
        NotiChat
    }

    public enum ChatType : int
    {
        Private, 
        World, 
        Local
    }

    public class LoginReq
    {
        public string id { get; set; }
        public string pwd { get; set; }
    }

    public class ChatMsg
    {
        public string talker { get; set; }
        public string msg { get; set; }
        public ChatType type { get; set; }
    }

    public class Character
    {
    }

    public class ComplexType
    {
        public int id { get; set; }
        public ChatMsg chatmsg { get; set; }
        public List<Character> my_characters { get; set; }
    }

    /*
    interface Rpc
    {
        Task<bool> Login(LoginReq req);
        Task<bool> Chat(ChatMsg req);
    }

    interface Noti
    {
        Task NotiChat(ChatMsg message);
    }
    */
}
